item { 
	name:'أ'
	id:1
}
item { 
	name:'ب'
	id:2
}
item { 
	name:'ت'
	id:3
}
item { 
	name:'ث'
	id:4
}
item { 
	name:'ج'
	id:5
}
item { 
	name:'ح'
	id:6
}
item { 
	name:'خ'
	id:7
}
item { 
	name:'د'
	id:8
}
item { 
	name:'ذ'
	id:9
}
item { 
	name:'ر'
	id:10
}
item { 
	name:'ز'
	id:11
}
item { 
	name:'س'
	id:12
}
item { 
	name:'ش'
	id:13
}
item { 
	name:'ص'
	id:14
}
item { 
	name:'ض'
	id:15
}
item { 
	name:'ط'
	id:16
}
item { 
	name:'ظ'
	id:17
}
item { 
	name:'ع'
	id:18
}
item { 
	name:'غ'
	id:19
}
item { 
	name:'ف'
	id:20
}
item { 
	name:'ق'
	id:21
}
item { 
	name:'ك'
	id:22
}
item { 
	name:'ل'
	id:23
}
item { 
	name:'م'
	id:24
}
item { 
	name:'ن'
	id:25
}
item { 
	name:'ه'
	id:26
}
item { 
	name:'و'
	id:27
}
item { 
	name:'ي'
	id:28
}
item { 
	name:'ال'
	id:29
}
item { 
	name:'ة'
	id:30
}
item { 
	name:'لا'
	id:31
}
item { 
	name:'ئ'
	id:32
}
